# based on the https://github.com/oauth2-proxy/ example
version: '3.2'

services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy.localtest.me
    volumes:
      - "./oauth2-proxy-keycloak.cfg:/oauth2-proxy.cfg:z"
    restart: unless-stopped
    networks:
      oauth2-proxy: {}
      httpbin: {}
      keycloak: {}
    depends_on:
      - httpbin
      - keycloak
    ports:
      - 4180:4180/tcp

  httpbin:
    container_name: httpbin
    image: kennethreitz/httpbin:latest
    hostname: httpbin.localtest.me
    networks:
      httpbin: {}

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:10.0.0
    hostname: keycloak.localtest.me
    command:
      [
        '-b',
        '0.0.0.0',
        '-Djboss.socket.binding.port-offset=1000',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/realm-config',
        '-Dkeycloak.migration.strategy=IGNORE_EXISTING',
      ]
    volumes:
      - ./keycloak:/realm-config:z
    environment:
      KEYCLOAK_USER: admin@example.com
      KEYCLOAK_PASSWORD: password
    networks:
      keycloak: {}
    ports:
      - 9080:9080/tcp

networks:
  httpbin: {}
  keycloak: {}
  oauth2-proxy: {}